version: '3'

services:
  eureka:
    image: maven:3.6.1-jdk-8
    ports:
      - '8761:8761'
    working_dir: /app
    volumes:
      - ./eureka-server:/app
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
    image: maven:3.6.1-jdk-8
    ports:
      - '8080:8080'
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=userdb
     - POSTGRES_DB=postdb
     - POSTGRES_DB=commentdb
  users-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '2121:2121'
    working_dir: /app
    volumes:
      - ./user-microservice:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  posts-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '2122:2122'
    working_dir: /app
    volumes:
      - ./post-microservice:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  comments-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '2123:2123'
    working_dir: /app
    volumes:
      - ./comment-microservice:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
