version: '3'

services:
  eureka:
    image: maven:3.6.1-jdk-8
    ports:
      - '8761:8761'
    working_dir: /app
    volumes:
      - ./eureka-server:/app
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  swagger:
    image: maven:3.6.1-jdk-8
    ports:
      - '3535:3535'
    volumes:
      - ./swagger:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  rabbitmq: 
    image: "rabbitmq:3-management"
    ports:
      - '5672:5672'
      - '15672:15672'
#    working_dir: /app
    volumes:
      - ./rabbit:/app
    # command: 'mvn spring-boot:run'
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest      
  api-gateway:
    image: maven:3.6.1-jdk-8
    ports:
      - '8080:8080'
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  postgresdev1:
    image: postgres
    ports:
     - "5435:5432"
    environment:
     - POSTGRES_PASSWORD=jmkc2002
     - POSTGRES_USER=jai
     - POSTGRES_DB=pguser
  postgresdev2:
    image: postgres
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_PASSWORD=jmkc2002
     - POSTGRES_USER=jai
     - POSTGRES_DB=pgpost
  postgresdev3:
    image: postgres
    ports:
     - "5434:5432"
    environment:
     - POSTGRES_PASSWORD=jmkc2002
     - POSTGRES_USER=jai
     - POSTGRES_DB=pgcomment
  postgresdev4:
    image: postgres
    ports:
     - "5436:5432"
    environment:
     - POSTGRES_PASSWORD=jmkc2002
     - POSTGRES_USER=jai
     - POSTGRES_DB=pggate
  users-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '2121:2121'
    working_dir: /app
    volumes:
      - ./user-microservice:/app
    depends_on:
      - eureka
      - rabbitmq
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  posts-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '2122:2122'
    working_dir: /app
    volumes:
      - ./post-microservice:/app
    depends_on:
      - eureka
      - rabbitmq
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  comments-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '2123:2123'
    working_dir: /app
    volumes:
      - ./comment-microservice:/app
    depends_on:
      - eureka
      - rabbitmq
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev